# cloudbuild.yaml
# Use the Cloud Native Buildpacks builder to build a Node.js image
steps:
  - name: "gcr.io/buildpacks/builder:v1"
    args:
      - "build"                            # invoke `pack build`
      - "-t"                               # tag flag
      - "gcr.io/$PROJECT_ID/sftp-fetch-job:latest"
      - "."                                # build the current directory
images:
  - "gcr.io/$PROJECT_ID/sftp-fetch-job:latest"
timeout: "1200s"
options:
  logging: CLOUD_LOGGING_ONLY
